SCHEMA_CLASS_RELATIONSHIPS = {
    "Report": "Article",
    "Article": "CreativeWork",
    "Message": "CreativeWork",
    "CreativeWork": "Thing",
    "Event": "Thing",
    "GovernmentOrganization": "Organization",
    "Organization": "Thing",
    "Invoice": "Intangible",
    "MonetaryAmount": "StructuredValue",
    "TextObject": "MediaObject",
    "MediaObject": "CreativeWork",
    "QuantitativeValue": "StructuredValue",
    "StructuredValue": "Intangible",
    "Occupation": "Intangible",
    "Order": "Intangible",
    "Intangible": "Thing",
    "Place": "Thing",
    "Person": "Thing",
    "VoteAction": "ChooseAction",
    "ChooseAction": "AssessAction",
    "AssessAction": "Action",
    "Action": "Thing",
}
