name: Continuous Integration
on:
  push:
  workflow_dispatch:
env:
  NODE_OPTIONS: "--max-old-space-size=4096"
jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Build packages
        run: npm run build:packages
      - name: Check types on apps
        run: npm run check-types:apps
      - name: Test
        run: npm run test
