name: Build and push Docker image
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-push-towndex-docker-image:
    name: Build and push towndex Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/towndex-gui/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/towndex:latest
